version: '3.9'

services:
  symp-nginx:
    image: nginx:latest
    container_name: ingress 
    volumes:
      - ./nginx/subdomains.conf:/etc/nginx/conf.d/subdomains.conf
      - ./nginx/localhost.conf:/etc/nginx/conf.d/localhost.conf
      - ./nginx/ssl/cert.crt:/etc/ssl/cert.crt 
      - ./nginx/ssl/private.pem:/etc/ssl/private.pem
      - ./nginx/ssl_wildcard/cert.crt:/etc/ssl_wildcard/cert.crt
      - ./nginx/ssl_wildcard/private.pem:/etc/ssl_wildcard/private.pem
    ports:
      - "80:80"
      - "443:443"
    networks:
        - symp
    restart: unless-stopped
    
networks:
    symp:
        external:
            name: symp
